### PR TITLE
Upgrade to go 1.16, add getting started section

### PR DESCRIPTION
**Pull request by jessicalins**
* Added `Getting started` section to README (basically copied over the comment from `TestInteractiveSetup` with small changes)
* Changed go version to 1.16
* I've ran `make deps`, `make all` and `make test-interactive` and it seems to run fine - not sure if I should test something else?

### CODE REVIEW

**Comment by jessicalins** [comment]
taking a look at CI, so added the do not merge label for now:)

**Comment by jessicalins** [comment]
I wonder if I should update here too: https://github.com/observatorium/api/blob/main/Dockerfile#L1

**Review by ianbillett — COMMENTED** [review]
Generally LGTM - you just need to update the dockerfile also :+1:

**Review by periklis — APPROVED** [review]
LGTM

**Pull request merged**
