### PR TITLE
support imagePullPolicy for observatorium-api.

### PR DESCRIPTION
**Pull request by morvencao**
This PR tries to make imagePullPolicy configurable in observatorium-api deployment.

Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Review by kakkoyun — APPROVED** [review]
LGTM

**Comment by kakkoyun** [comment]
@morvencao It would be amazing to write some description in the PR to document the reasoning behind the change. Otherwise, I don't see any reasons why we shouldn't have it.

**Comment by morvencao** [comment]
Updated the PR description, thanks @kakkoyun for the kind reminder.
I thought the PR is self-explanatory, anyway adding detailed description is usual practice.

**Pull request merged**
